name: Issue Information
on: 
    issues:
        types: created
jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
        - name: Detail Issue Created
          run: |
            echo "Issue title: ${{ github.event.issue.title }}"
            echo "Issue body: ${{ github.event.issue.body }}"
            echo "Issue creator: ${{ github.event.issue.user.login }}"